org: andreidobre
app: crash-course
service: aws-node-http-api-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    # DynamoDB read/write role permissions for TodoTable table
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:us-west-2:574238409071:table/TodoTable

functions:
  addTodo:
    handler: src/handlers/addTodo.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  getTodos:
    handler: src/handlers/getTodos.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  getTodo:
    handler: src/handlers/getTodo.handler
    events:
      - http:
          path: /{id}
          method: get
          cors: true
  updateTodo:
    handler: src/handlers/updateTodo.handler
    events:
      - http:
          path: /{id}
          method: put
          cors: true
  deleteTodo:
    handler: src/handlers/deleteTodo.handler
    events:
      - http:
          path: /{id}
          method: delete
          cors: true

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH # partition key
